### ISSUE TITLE
Add ability to selectively enable/disable

### ISSUE THREAD

**Issue by tacman** [zenstruck/messenger-monitor-bundle#58]
I'd like to only enable the monitor in certain situations, but want to keep it in bundles.php (so routing and dependency injection works, even if not enabled).

it looks like there's only the ability to disable live-components

```yaml
zenstruck_messenger_monitor:
    live_components:
        enabled: false
        role: ROLE_MESSENGER_MONITOR

```
