### ISSUE TITLE
Why I don't see the Processed Messages ?

### ISSUE THREAD

**Issue by Proglab** [zenstruck/messenger-monitor-bundle#75]
Hello,

I install your bundle and Worker Status and Transports is ok but Processed Messages still empty

![image](https://github.com/zenstruck/messenger-monitor-bundle/assets/4598760/d2cbb5bc-57f7-46ca-817c-f808c3ebd621)

Here is my configs :

```yml


zenstruck_messenger_monitor:
  live_components:
    enabled: true

    # Role required to view live components.
    role: ROLE_ADMIN
  storage:
    orm:
      entity_class: App\Entity\ProcessedMessage
```
```yml
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            '*': async
```

The processed_messages table stay empty.

I use RabbitMQ

Do you need other informations ?

Thank you
