### ISSUE TITLE
Mapping Doctrine of superclass ProcessedMessage doesn't work

### ISSUE THREAD

**Issue by Fofonew** [zenstruck/messenger-monitor-bundle#80]
When i do the command `bin/console doctrine:mapping:info` i see 

```
bin/console doctrine:mapping:info
 Found 10 mapped entities:

 [OK]   App\Entity\AnonHistory
 [OK]   App\Entity\RequestHistory
 [OK]   App\Entity\SyncTrack
 [OK]   App\Entity\AnonHistoryAnonymizerStatus
 [OK]   App\Entity\Customer
 [OK]   App\Entity\ProcessedMessage
 [OK]   App\Entity\Activity
 [OK]   App\Entity\SyncType
 [OK]   App\Entity\ActivityType
 [OK]   Zenstruck\Messenger\Monitor\History\Model\ProcessedMessage
```
This is my entity file

```php
<?php

// src/Entity/ProcessedMessage.php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zenstruck\Messenger\Monitor\History\Model\ProcessedMessage as BaseProcessedMessage;

#[ORM\Entity(readOnly: true)]
#[ORM\Table('processed_messages')]
class ProcessedMessage extends BaseProcessedMessage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function id(): ?int
    {
        return $this->id;
    }
}
``` 

but when i generate migration i got :

```php
$this->addSql('CREATE SEQUENCE processed_messages_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE processed_messages (id INT NOT NULL, PRIMARY KEY(id))');
```

**Comment by kbond** [comment]
Hi @Fofonew, did you add the following config:

```yaml
# config/packages/zenstruck_messenger_monitor.yaml

zenstruck_messenger_monitor:
    storage:
        orm:
            entity_class: App\Entity\ProcessedMessage
```

_(and clear cache after?)_
